-- Active: 1751016462714@@127.0.0.1@3306@crud_db2
DROP DATABASE IF EXISTS crud_db2;
CREATE DATABASE crud_db2 DEFAULT CHARACTER SET utf8mb4;
USE crud_db2;

CREATE TABLE users(
    num INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    school VARCHAR(100) NOT NULL,
    user_id VARCHAR(100) NOT NULL UNIQUE,
    user_pw VARCHAR(100) NOT NULL
);

ALTER TABLE users MODIFY COLUMN user_pw VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN profile_image VARCHAR(255);


CREATE TABLE posts(
    num INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    written_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

ALTER TABLE posts ADD post_pw VARCHAR(255);
ALTER TABLE posts ADD file_name VARCHAR(255);

